name: Desplegar Vite App a GitHub Pages
on:
   workflow_dispatch: # Este evento permite ejecutar el flujo de trabajo manualmente
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PERSONALTOKEN }}
          publish_dir: ./dist
